name: build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up JDK 12 for Packaging
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'

    - name: Package Producer with Maven
      working-directory: producer
      run: mvn --batch-mode package --file pom.xml -D skipTests

    - name: Package Consumer with Maven
      working-directory: consumer
      run: mvn --batch-mode package --file pom.xml -D skipTests

    - name: Build Producer Docker image
      uses: docker/build-push-action@v1
      with:
        path: producer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: juliocesarmidia/kafka-producer
        tag_with_ref: false
        tag_with_sha: true

    - name: Build Consumer Docker image
      uses: docker/build-push-action@v1
      with:
        path: consumer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: juliocesarmidia/kafka-consumer
        tag_with_ref: false
        tag_with_sha: true
