name: publish_release

on:
  release:
    branches: [ main, development ]
    types: [ created ]

jobs:
  publish:
    name: Publish Release
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/publish' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up JDK 12 for Producer
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'

      - name: Publish Producer to GitHub Packages
        working-directory: producer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode deploy
        # https://maven.pkg.github.com/juliocesarscheidt/java-kafka-project/com/github/juliocesarscheidt/kafka-project/0.0.1/kafka-project-producer-0.0.1.jar

      - name: Publish Consumer to GitHub Packages
        working-directory: consumer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode deploy
        # https://maven.pkg.github.com/juliocesarscheidt/java-kafka-project/com/github/juliocesarscheidt/kafka-project/0.0.1/kafka-project-consumer-0.0.1.jar
